### PR TITLE
docs(reference): rename incorrectly named page in readme

### PR DESCRIPTION
**Pull request by Looskie**
Hope you are well!

### CODE REVIEW

**Comment by alii** [comment]
image
lgtm

**Review by alii — APPROVED** [review]

**Comment by heybereket** [comment]
image
lgtm

**Review by heybereket — APPROVED** [review]

**Comment by pxseu** [comment]
image
lgtm

**Review by pxseu — APPROVED** [review]

**Comment by robertt** [comment]
image
lgtm

**Review by robertt — APPROVED** [review]

**Review by steebchen — APPROVED** [review]
aye

**Comment by Hexiro** [comment]
image
### Thanks for merge 🚀

**Comment by Looskie** [comment]
image
Thanks for merge 🚀

**Comment by Looskie** [comment]
image
<h3>Thanks for merge 🚀</h3>

**Comment by alii** [comment]
image

# Thanks for merge

**Comment by Looskie** [comment]
image
<h4>Thanks for merge </h4>

**Comment by heybereket** [comment]
image
Thanks for merge

**Comment by bfu4** [comment]
### Thanks for merge

**Pull request merged**
